### ISSUE TITLE
民间资料汇总

### ISSUE THREAD

**Issue by Linklinkguan** [lyricat/call-for-health#3]
【最全整理】湖北防疫需求与民间援助信息、捐款渠道汇总
https://shimo.im/docs/cRrJwHdGXdX9CP8x/read

**Comment by riririridiculous** [comment]
> 【最全整理】湖北防疫需求与民间援助信息、捐款渠道汇总
> https://shimo.im/docs/cRrJwHdGXdX9CP8x/read

该文档可查询到的内容如下：
![image](https://user-images.githubusercontent.com/39544891/73129178-a895be00-4018-11ea-9e29-ea0106054c49.png)

**Comment by lyricat** [comment]
原则上，不要在这里提交数据。
