### ISSUE TITLE
权限与角色

### ISSUE THREAD

**Issue by lyricat** [lyricat/call-for-health#4]
系统中存在几种角色：

1. 管理员，目前由我来做，不进入系统实现，负责系统的研发运维。
2. 志愿者，所有的志愿者，有权限发布需求、改变需求状态，需要注册和实名
3. 用户，可发布信息，但是信息进入 pending 状态，由志愿者来核实，需要注册和实名
4. 浏览者，可以查看站点中的公开需求，不需要注册

**Comment by leinue** [comment]
用户访问控制和授权没必要自己做，建议用  [Authing.cn](https://authing.cn) 来做，能很快实现好。
以下两个文档供参考：
1. https://docs.authing.cn/authing/quickstart/implement-sso-with-authing
2. https://docs.authing.cn/authing/advanced/roles

**Comment by lyricat** [comment]
> 用户访问控制和授权没必要自己做，建议用 [Authing.cn](https://authing.cn) 来做，能很快实现好。
> 以下两个文档供参考：
> 
>     1. https://docs.authing.cn/authing/quickstart/implement-sso-with-authing
> 
>     2. https://docs.authing.cn/authing/advanced/roles

没事，我先弄个脚手架出来。可以随时改。

**Comment by leinue** [comment]
> > 用户访问控制和授权没必要自己做，建议用 [Authing.cn](https://authing.cn) 来做，能很快实现好。
> > 以下两个文档供参考：
> > ```
> > 1. https://docs.authing.cn/authing/quickstart/implement-sso-with-authing
> > 
> > 2. https://docs.authing.cn/authing/advanced/roles
> > ```
> 
> 没事，我先弄个脚手架出来。可以随时改。

造轮子没啥意义吧，怎么快怎么来比较好

**Comment by lyricat** [comment]
做完了。
